services:
  promiumjsoneditor:
    image: promiumjsoneditor
    container_name: promiumjsoneditor
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - NODE_ENV=production